### ISSUE TITLE
New update causes the bot to crash without booting 

### ISSUE THREAD

**Issue by HexadecimalPython** [nekonez/discord.htc#1]
module.js:457

    throw err;
    ^

Error: Cannot find module './structs/voice/VoiceServer'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)

**Comment by nekonez** [comment]
possibly fixed, npm package published
